improve error and interruptions

diff --git a/templates/backup.sh.j2 b/templates/backup.sh.j2
--- a/templates/backup.sh.j2
+++ b/templates/backup.sh.j2
@@ -34,10 +34,11 @@ while [ $RETRY_COUNT -le $TRY_MAX ]; do
     {% else %}
         {% if backup_lvm_snapshot=="true" %}
             echo "Creating LVM snapshot for backup..."
-            lvcreate --size {{ backup_lvm_snapshot_size }} --snapshot --name {{ backup_lvm_snapshot_name }} {{ backup_lvm_snapshot_volume }}
+            lvcreate --size {{ backup_lvm_snapshot_size }} --snapshot --name {{ backup_lvm_snapshot_name }} {{ backup_lvm_snapshot_volume }} || { echo "Snapshot creation failed."; exit 1; }
             mkdir -p {{ backup_lvm_snapshot_mount_point }}
             echo "Mounting LVM snapshot..."
-            mount /dev/ubuntu-vg/{{ backup_lvm_snapshot_name }} {{ backup_lvm_snapshot_mount_point }}
+            mount /dev/ubuntu-vg/{{ backup_lvm_snapshot_name }} {{ backup_lvm_snapshot_mount_point }} || { echo "Mount failed."; lvremove -fy /dev/ubuntu-vg/{{ backup_lvm_snapshot_name }}; exit 1; }
+            trap 'echo "Cleaning up..."; umount {{ backup_lvm_snapshot_mount_point }}; lvremove -fy /dev/ubuntu-vg/{{ backup_lvm_snapshot_name }}' EXIT
             echo "Creating archive from LVM snapshot..."
             ERROR=$($TAR \
             --exclude-from='{{ backup_path }}/backup-exclude.txt' \
